### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by ner00** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#15] opened 2024-03-17 03:28 UTC
1. The about page has a typo, "nsertmorecoins.es" hyperlink is mistakenly missing the first letter, it should be "insertmorecoins.es";

2. This is an issue with the "Supermodel.ini" config file distributed with the latest release, so it is not an issue directly related to this software. The config distributed has `WindowXPosition=-1920` - which I imagine is because you have a 1920x1080 resolution and a secondary monitor to your left - but for me, with a single monitor at the same resolution, it made the window "invisible". Given the negative value, I assume it would also be "invisible" for someone with a 1080p primary monitor and a secondary monitor to their right instead of their left.

**Comment by BackPonBeauty** [comment] 2024-03-18 15:26
oh hello
I was away for 3 days due to work.
1. is a typo. It must have been lost at some point.
2. I was wrong in my initial reaction on this one.
The problem is that I included a config folder in my release file.
This gave me a hint on how to solve this problem. I believe this issue will be resolved in the next release.

thanks

ポン美💛

**Comment by BackPonBeauty** [comment] 2024-03-26 02:35
I think this issue is resolved at 1.0.7.3

**Closed by BackPonBeauty** 2024-03-26 02:35 UTC

**Comment by ner00** [comment] 2024-03-29 19:18
> I think this issue is resolved at 1.0.7.3

The typo in the "About" dialog is still present.
